import { User, Property, UserRoleAssignment } from '../../types';

const adminRole: UserRoleAssignment = {
    id: 'role-001',
    userId: 'user-001',
    role: 'super_admin',
    grantedAt: new Date().toISOString(),
    grantedBy: 'system',
    isActive: true
};

const ownerRole: UserRoleAssignment = {
    id: 'role-002',
    userId: 'user-002',
    role: 'owner',
    grantedAt: new Date().toISOString(),
    grantedBy: 'system',
    isActive: true
};

const renterRole: UserRoleAssignment = {
    id: 'role-003',
    userId: 'user-003',
    role: 'renter',
    grantedAt: new Date().toISOString(),
    grantedBy: 'system',
    isActive: true
};

export const MOCK_USERS: User[] = [
    {
        id: 'user-001',
        email: 'admin@gradea.realty',
        firstName: 'System',
        lastName: 'Admin',
        phone: null,
        avatarUrl: null,
        status: 'active',
        emailVerified: true,
        phoneVerified: true,
        kycStatus: 'verified',
        kycVerifiedAt: new Date().toISOString(),
        twoFactorEnabled: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        lastLoginAt: new Date().toISOString(),
        roles: [adminRole]
    },
    {
        id: 'user-002',
        email: 'owner@example.com',
        firstName: 'John',
        lastName: 'Owner',
        phone: null,
        avatarUrl: null,
        status: 'active',
        emailVerified: true,
        phoneVerified: true,
        kycStatus: 'verified',
        kycVerifiedAt: new Date().toISOString(),
        twoFactorEnabled: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        lastLoginAt: new Date().toISOString(),
        roles: [ownerRole]
    },
    {
        id: 'user-003',
        email: 'renter@example.com',
        firstName: 'Jane',
        lastName: 'Renter',
        phone: null,
        avatarUrl: null,
        status: 'active',
        emailVerified: true,
        phoneVerified: false,
        kycStatus: 'verified',
        kycVerifiedAt: new Date().toISOString(),
        twoFactorEnabled: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        lastLoginAt: new Date().toISOString(),
        roles: [renterRole]
    }
];

export const MOCK_PROPERTIES: Property[] = [
    {
        id: 'prop-001',
        title: 'Modern Villa Estate',
        description: 'Stunning modern villa...',
        listingType: 'sale',
        propertyType: 'house',
        status: 'active',
        salePrice: 3450000,
        rentPrice: null,
        rentPeriod: null,
        depositAmount: null,
        bedrooms: 5,
        bathrooms: 4,
        squareFeet: 4200,
        lotSize: 8000,
        yearBuilt: 2020,
        parkingSpaces: 3,
        city: 'Beverly Hills',
        state: 'CA',
        postalCode: '90210',
        country: 'USA',
        addressLine1: '1234 Beverly Drive',
        addressLine2: null,
        latitude: 34.0736,
        longitude: -118.4004,
        images: [
            { id: 'img1', propertyId: 'prop-001', url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600', isPrimary: true, caption: 'Front', displayOrder: 0, mimeType: 'image/jpeg', thumbnailUrl: null, width: 1600, height: 1200, fileSize: 1024, uploadedAt: new Date().toISOString() },
            { id: 'img2', propertyId: 'prop-001', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', isPrimary: false, caption: 'Pool', displayOrder: 1, mimeType: 'image/jpeg', thumbnailUrl: null, width: 800, height: 600, fileSize: 1024, uploadedAt: new Date().toISOString() }
        ],
        amenities: [],
        ownerId: 'user-002',
        availableFrom: null,
        leaseTermMonths: null,
        instantBooking: false,
        approvedAt: new Date().toISOString(),
        approvedBy: 'system',
        rejectionReason: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),

        // Investment data
        estimatedAnnualIncome: 180000,
        estimatedExpenses: 45000,
        capRate: 5.2,
        estimatedRoi: 7.5,
        hoaFees: 0,
        propertyTax: 4500
    },
    {
        id: 'prop-002',
        title: 'Luxury Penthouse',
        description: 'Exquisite penthouse...',
        listingType: 'sale',
        propertyType: 'condo',
        status: 'active',
        salePrice: 5200000,
        rentPrice: null,
        rentPeriod: null,
        depositAmount: null,
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: 3800,
        lotSize: 0,
        yearBuilt: 2019,
        parkingSpaces: 2,
        city: 'New York',
        state: 'NY',
        postalCode: '10022',
        country: 'USA',
        addressLine1: '432 Park Avenue',
        addressLine2: null,
        latitude: 40.7614,
        longitude: -73.9776,
        images: [
            { id: 'img3', propertyId: 'prop-002', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600', isPrimary: true, caption: 'Living Room', displayOrder: 0, mimeType: 'image/jpeg', thumbnailUrl: null, width: 1600, height: 1200, fileSize: 1024, uploadedAt: new Date().toISOString() }
        ],
        amenities: [],
        ownerId: 'user-002',
        availableFrom: null,
        leaseTermMonths: null,
        instantBooking: false,
        approvedAt: new Date().toISOString(),
        approvedBy: 'system',
        rejectionReason: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),

        estimatedAnnualIncome: 264000,
        estimatedExpenses: 80000,
        capRate: 5.1,
        estimatedRoi: 6.8,
        hoaFees: 2500,
        propertyTax: 8000
    },
    {
        id: 'prop-003',
        title: 'Urban Smart Home',
        description: 'State-of-the-art smart home...',
        listingType: 'rent',
        propertyType: 'house',
        status: 'active',
        salePrice: null,
        rentPrice: 3200,
        rentPeriod: 'monthly',
        depositAmount: 3200,
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: 2400,
        lotSize: 3000,
        yearBuilt: 2021,
        parkingSpaces: 2,
        city: 'Seattle',
        state: 'WA',
        postalCode: '98101',
        country: 'USA',
        addressLine1: '890 Pike Street',
        addressLine2: null,
        latitude: 47.6101,
        longitude: -122.3421,
        images: [
            { id: 'img4', propertyId: 'prop-003', url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1600', isPrimary: true, caption: 'Exterior', displayOrder: 0, mimeType: 'image/jpeg', thumbnailUrl: null, width: 1600, height: 1200, fileSize: 1024, uploadedAt: new Date().toISOString() }
        ],
        amenities: [],
        ownerId: 'user-002',
        availableFrom: new Date().toISOString(),
        leaseTermMonths: 12,
        instantBooking: true,
        approvedAt: new Date().toISOString(),
        approvedBy: 'system',
        rejectionReason: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),

        estimatedAnnualIncome: 38400,
        estimatedExpenses: 5000,
        capRate: null,
        estimatedRoi: null,
        hoaFees: 0,
        propertyTax: 3000
    }
];
