
-- NUCLEAR OPTION: Reset Properties to Simple Schema
-- Run this to fix "Column does not exist" errors

-- 1. Clean up old dependencies first
DROP TABLE IF EXISTS property_images CASCADE;
DROP TABLE IF EXISTS properties CASCADE;

-- 2. Create the Simple Table (Matches Frontend Code)
CREATE TABLE properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  price NUMERIC NOT NULL,
  address TEXT,
  beds INT,
  baths INT,
  sqft INT,
  image_url TEXT,
  type TEXT CHECK (type IN ('buy', 'rent')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Security (Allow Public Read)
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public properties are viewable by everyone" ON properties;
CREATE POLICY "Public properties are viewable by everyone" 
ON properties FOR SELECT 
USING (true);

-- 4. Seed Data
INSERT INTO properties (title, price, address, beds, baths, sqft, image_url, type)
VALUES
  ('Modern Villa Estate', 3450000, '123 Beverly Dr, Beverly Hills, CA', 5, 4, 4200, 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80', 'buy'),
  ('Downtown Penthouse', 5200000, '432 Park Ave, New York, NY', 3, 3, 2800, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80', 'buy'),
  ('Seaside Retreat', 1850000, '78 Ocean Blvd, Miami, FL', 4, 3, 3100, 'https://images.unsplash.com/photo-1600596542815-e3288e6a2b84?auto=format&fit=crop&w=800&q=80', 'buy');
