
-- Option B: Saved Properties Table
-- Stores user favorites

CREATE TABLE IF NOT EXISTS saved_properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL, -- References the user from your auth system
  property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, property_id)
);

-- Security: Enable RLS
ALTER TABLE saved_properties ENABLE ROW LEVEL SECURITY;

-- MVP Policy: Open access (since we are handling auth check in app logic)
-- In a strict prod env, we would use strict RLS policies linked to auth.uid()
DROP POLICY IF EXISTS "Enable all access for saved_properties" ON saved_properties;
CREATE POLICY "Enable all access for saved_properties" ON saved_properties FOR ALL USING (true);
